[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = false

solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

gas_reports = ["*"]
verbosity = 3

[profile.ci]
verbosity = 3
fuzz = { runs = 1000 }

[fmt]
tab_width = 2
line_length = 120

single_line_statement_blocks = "preserve"
multiline_func_header = "params_first_multi"

bracket_spacing = true
quote_style = "single"
sort_imports = true

int_types = "long"
number_underscore = "thousands"
pow_no_space = true

docs_style = "block"
wrap_comments = true

